### ISSUE TITLE
修正case_special_ratio百分比分母計算方式

### ISSUE THREAD

**Issue by DinDinSS** [KaoCC/AutoScript#16]
case_special_ratio，百分比計算方式，分母應為該項註記之件數，如106年採購貪瀆案件分析總數為16件，該註記營建類為3件(營建類全部為8件)，百分比為3/16=18.75%，非3/8=37.5%！

**Comment by KaoCC** [comment]
@DinDinSS 
因為現在百分比計算方式是：個別項目 除以 該列(row)總和，下一版本中 該表格將會行列互換。

**Comment by KaoCC** [comment]
關聯版本 v2.2

**Comment by KaoCC** [comment]
@DinDinSS 

fixed.

但檔名沒有改, 還是叫case_special_
