### ISSUE TITLE
法條錯格時，程式可否警告

### ISSUE THREAD

**Issue by DinDinSS** [KaoCC/AutoScript#17]
當貪瀆法條空白，刑法132寫到最後一格，程式判別為”其他“，可否增加警告，使使用者可藉此修正！

**Comment by KaoCC** [comment]
@DinDinSS 
因最後一格「其他」法條的比對規則無明確定義，且該格可能出現的情況很多，每一種情況並不絕對互斥(mutually exclusive)，故只能以數字為憑藉將任何可疑的都列出。
可在下版本中加入此功能。

**Comment by KaoCC** [comment]
改為當其他格讀出屬於刑法格的內容時報錯

**Comment by KaoCC** [comment]
@DinDinSS 
不報錯，改為警告
