### ISSUE TITLE
程式文字可否複製?

### ISSUE THREAD

**Issue by DinDinSS** [KaoCC/AutoScript#18]
main黑框內文字可否按右鍵複製?

**Comment by KaoCC** [comment]
@DinDinSS 
參考以下：

[link 1](https://www.howtogeek.com/howto/windows-vista/copy-to-the-clipboard-from-the-windows-command-prompt/)
[link 2](https://superuser.com/questions/295370/how-to-copy-text-in-the-windows-command-line-cmd)
[link 3](https://stackoverflow.com/questions/11543578/copy-text-from-a-windows-cmd-window-to-clipboard)
[link 4](https://answers.microsoft.com/zh-hant/windows/forum/windows_7-files/命令提示字/97d2d0d2-ad06-410d-a297-cdc92b3feac8)

**Comment by KaoCC** [comment]
problem resolved.
