### ISSUE TITLE
法條合併儲存格可否警告

### ISSUE THREAD

**Issue by DinDinSS** [KaoCC/AutoScript#19]
法條欄合併儲存格時，程式可否警告修正?！

**Comment by DinDinSS** [comment]
弊端類型、特殊貪瀆案件註記、性別、主管機關、職務層級，倘若合併儲存格，是否皆不影響結果?

**Comment by KaoCC** [comment]
- 幾乎無法警告或是做其他檢查，因為三種涉案類型中皆有可能是空格。 但可以在三者皆為空格時報錯。

- 程式在做第一種案件分析時，會將所以可疑的情況羅列，那些警告有些就是自合併格造成，不過應該不影響結果，但為避免拆解格式時發生意料之外的錯誤盡量不要合併。若不放心可以檢查raw_df中對應的編號位置看看資料是否正常

**Comment by KaoCC** [comment]
1. fixed
