### ISSUE TITLE
law_out數字與law_df對不起來(驚驚)

### ISSUE THREAD

**Issue by DinDinSS** [KaoCC/AutoScript#21]
law_df經過篩選跟紙本數字相同，惟law_level_out出現數字不同

**Comment by KaoCC** [comment]
關聯版本 v2.2, 輸入資料106年度。  尚待確認

**Comment by KaoCC** [comment]
415

**Comment by KaoCC** [comment]
法條錯位問題(非415)已解，此為程式嘗試刪去多餘的空白欄所致，現在都不會過濾NaN

**Comment by KaoCC** [comment]
已找到判讀錯誤的法條個案，以後會採嚴格作法，不在名單內的法條都會報錯。

**Comment by KaoCC** [comment]
fixed
