### ISSUE TITLE
法條判別與result不一樣@@

### ISSUE THREAD

**Issue by DinDinSS** [KaoCC/AutoScript#22]
target法條第三格及law_df顯示為洗錢防制法，result判別為-1?

**Comment by KaoCC** [comment]
現在-1跟0都有可能是「其他」的情況，分別將-1跟0出現的個數相加即可。

就其他格而言：
-1是指該格中沒有明顯的符合判例，0是有在預設的判例之中，但因為所謂「其他」格本來就無規則可言，所謂「預設判例」也只是我自己假定測試用的。

**Comment by DinDinSS** [comment]
-1是指該格中沒有明顯的符合判例，0是有在預設的判例之中，但因為所謂「其他」格本來就無規則可言，所謂「預設判例」也只是我自己假定測試用的。-＞＞現在有預設判例為0的態樣是什麼??分不出來0或-1的情形！

**Comment by KaoCC** [comment]
正規表示法： 第?(\d{3})\s*(?:條)?

這是一個測試用的判斷法，目的只是先加在這裡當作placeholder，本來要等之後有明確的規則時再修改，譬如從較寬鬆的規則中砍去較嚴格、絕對不符合的例子等。

就該正規表示法而言：
其中「第」跟「條」是可忽略字，惟數字一定是三位數，數字後可以有若干空格
舉例說明，以上規則會判斷下列字串為符合案件：

第213條
第212    條
213條
第134
567

又因為判斷方式是採最寬鬆的全區判斷(find all)，因此「第」之前接什麼字的會是符合的：

如：
刑法第134條   <= (注意此例，因此他目前很難警告刑法例打錯格的情況)
奇怪法第100條

皆會被認出。

下列字串為不符合案件：
第3
15條
22
國家機密
第4條第5項第1款



結論是目前你不需要特別去區分-1跟0個別表示什麼，都把他們當作「其他」加總就好

**Comment by DinDinSS** [comment]
那程式出現 [error] Data at row index A causes an error while matching 其他!Data: 奇怪法第XX條第O項，就自動忽略?

**Comment by KaoCC** [comment]
再之後版本中重新調整警告訊息的輸出方式：

其他欄因為無規則  任何情況都預設判讀為0, 若有213則判讀213

**Comment by KaoCC** [comment]
@DinDinSS 
新增個別法條欄位判讀規則，現在採更嚴格的方式:

貪瀆: 數值在 40000 ~ 70000 或 110000 ~ 150000 間則通過, 否則錯誤

刑法: 數值在1200000 ~ 1340000則通過, 否則錯誤

其他: 數值為213則通過並回傳213, 否則通過並回傳0, 另外警告格子中是否有120 ~ 134
