### ISSUE TITLE
law_level_out跟law_agency_out，法條表示方法修正

### ISSUE THREAD

**Issue by DinDinSS** [KaoCC/AutoScript#33]
協助標示0、-1、-2、-3表達的意義！

**Comment by KaoCC** [comment]
@DinDinSS 

任何下列形式的檔案名稱：Y_X_out，皆表示excel檔案中 以Y為列索引(row index)對以X為行索引(column index)之輸出結果。再者，任何列跟行的索引值都是由同一資料夾下的同名文字檔控制索引內容。

以law_level_out為例，law法條是row index, level職級是column index，固可搜尋law_row.txt以及level_col.txt來修改索引內容。

在法條law中，0、-1、-2、-3是對於法條的判讀註記，其中0表示在檢查「其他」欄填入的法條中，該法條判讀為「其他法」，-1表示任何形式的錯誤，-2表示該項為國家機密，-3是保留項暫時不使用(可以在law_row.txt中移除)。

上述內容整理後將註記在wiki

**Comment by KaoCC** [comment]
[檔名意義簡述](https://github.com/KaoCC/AutoScript/wiki/%E6%AA%94%E5%90%8D%E6%84%8F%E7%BE%A9%E7%B0%A1%E8%BF%B0)
